In [1]:
import pandas as pd

In [2]:
data_type = {"gameId": str, "teamId": str}
df_stat = pd.read_csv('../dataset/merged_team_stats.csv', dtype=data_type )
df_stat

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98.0,0.401
1,21300001,1610612754,2013-10-29,IND vs. ORL,W,1,0,1.000,240,34,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
2,21300002,1610612748,2013-10-29,MIA vs. CHI,W,1,0,1.000,240,37,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
3,21300003,1610612747,2013-10-29,LAL vs. LAC,W,1,0,1.000,240,42,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
4,21300001,1610612753,2013-10-29,ORL @ IND,L,0,1,0.000,240,36,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25943,22300961,1610612756,2024-03-15,PHX @ CHA,W,39,28,0.582,240,40,...,10.5,0.523,0.558,1.0,0.198,97.34,95.0,79.17,95.0,0.591
25944,22300962,1610612748,2024-03-15,MIA @ DET,W,36,30,0.545,240,43,...,8.2,0.511,0.539,1.0,0.196,99.42,98.0,81.67,98.0,0.556
25945,22300963,1610612761,2024-03-15,TOR vs. ORL,L,23,44,0.343,240,38,...,16.5,0.556,0.573,1.0,0.198,97.74,97.5,81.25,97.0,0.437
25946,22300965,1610612743,2024-03-15,DEN @ SAS,W,47,20,0.701,240,49,...,13.3,0.607,0.620,1.0,0.198,99.08,98.0,81.67,98.0,0.578
25947,22300964,1610612740,2024-03-15,NOP vs. LAC,W,40,26,0.606,240,42,...,9.5,0.557,0.585,1.0,0.200,95.58,94.5,78.75,95.0,0.528

In [3]:
df_chicago = df_stat[df_stat['teamId'] == "1610612741"]
df_chicago.reset_index(drop=True, inplace=True)
df_chicago

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.50,82.08,98.0,0.401
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.00,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.50,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.00,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.00,77.50,93.0,0.756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,22300907,1610612741,2024-03-07,CHI @ GSW,W,31,32,0.492,240,46,...,13.6,0.621,0.644,1.0,0.198,105.72,103.50,86.25,103.0,0.508
856,22300917,1610612741,2024-03-09,CHI @ LAC,L,31,33,0.484,240,37,...,12.6,0.506,0.540,1.0,0.201,96.64,94.50,78.75,95.0,0.434
857,22300935,1610612741,2024-03-11,CHI vs. DAL,L,31,34,0.477,240,35,...,13.8,0.433,0.466,1.0,0.199,96.64,94.50,78.75,94.0,0.313
858,22300948,1610612741,2024-03-13,CHI @ IND,W,32,34,0.485,265,48,...,10.8,0.576,0.622,1.0,0.198,100.71,100.53,83.77,111.0,0.516
859,22300956,1610612741,2024-03-14,CHI vs. LAC,L,32,35,0.478,240,41,...,14.0,0.570,0.597,1.0,0.198,92.60,92.00,76.67,93.0,0.419

In [4]:
index = 11
df_last_10_games = df_chicago.iloc[max(0, index - 10):index]
df_last_10_games

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.0,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.5,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.0,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.0,77.50,93.0,0.756
5,21300102,1610612741,2013-11-11,CHI vs. CLE,W,3,3,0.500,240,34,...,12.5,0.434,0.508,1.0,0.201,92.12,88.0,73.33,88.0,0.640
6,21300126,1610612741,2013-11-15,CHI @ TOR,W,4,3,0.571,240,36,...,18.5,0.494,0.543,1.0,0.196,95.52,92.5,77.08,92.0,0.615
7,21300140,1610612741,2013-11-16,CHI vs. IND,W,5,3,0.625,240,40,...,16.7,0.576,0.614,1.0,0.195,95.94,90.5,75.42,90.0,0.610
8,21300151,1610612741,2013-11-18,CHI vs. CHA,W,6,3,0.667,240,27,...,17.2,0.400,0.485,1.0,0.203,95.34,92.5,77.08,93.0,0.564
9,21300175,1610612741,2013-11-21,CHI @ DEN,L,6,4,0.600,240,38,...,18.8,0.403,0.418,1.0,0.195,98.42,96.5,80.42,96.0,0.416
10,21300185,1610612741,2013-11-22,CHI @ POR,L,6,5,0.545,240,32,...,17.2,0.416,0.496,1.0,0.197,95.68,92.0,76.67,93.0,0.463

In [5]:
game_id = df_last_10_games['gameId'][10]
print(game_id)

21300185

In [6]:

nb_wins = (df_last_10_games['WL'] == 'W').sum()
print(nb_wins)
pct_tir = df_last_10_games['PCT_TIR_REUSSI'].mean()
print(pct_tir)
pct_3pt = df_last_10_games['PCT_3PTS'].mean()
print(pct_3pt)
pct_lf = df_last_10_games['PCT_LANCER_FRANC'].mean()
print(pct_lf)
e_offensive_rating = df_last_10_games['estimatedOffensiveRating'].mean()
print(e_offensive_rating)
offensive_rating = df_last_10_games['offensiveRating'].mean()
print(offensive_rating)
e_defensive_rating = df_last_10_games['estimatedDefensiveRating'].mean()
print(e_defensive_rating)
defensive_rating = df_last_10_games['defensiveRating'].mean()
print(defensive_rating)
e_net_rating = df_last_10_games['estimatedNetRating'].mean()
print(e_net_rating)
net_rating = df_last_10_games['netRating'].mean()
print(net_rating)
ast_pct = df_last_10_games['assistPercentage'].mean()
print(ast_pct)
ast_to_tov = df_last_10_games['assistToTurnover'].mean()
print(ast_to_tov)
ast_ratio = df_last_10_games['assistRatio'].mean()
print(ast_ratio)
e_tov_ratio = df_last_10_games['estimatedTeamTurnoverPercentage'].mean()
print(e_tov_ratio)
tov_ratio = df_last_10_games['turnoverRatio'].mean()
print(tov_ratio)
effective_field_goal_percentage = df_last_10_games['effectiveFieldGoalPercentage'].mean()
print(effective_field_goal_percentage)
true_shooting_percentage = df_last_10_games['trueShootingPercentage'].mean()
print(true_shooting_percentage)
e_pace = df_last_10_games['estimatedPace'].mean()
print(e_pace)
pace = df_last_10_games['pace'].mean()
print(pace)
pace_per_40 = df_last_10_games['pacePer40'].mean()
print(pace_per_40)
pie = df_last_10_games['PIE'].mean()
print(pie)

6
0.4244
0.3534
0.8279
98.25999999999999
101.02
92.86999999999999
96.04
5.360000000000001
4.96
0.604
1.274
16.060000000000002
17.8112
18.28
0.4558
0.5118
95.298
92.45
77.04199999999999
0.5501

In [7]:
df_chicago

,gameId,teamId,GAME_DATE,DUEL,WL,NB_VICTOIRE,NB_DEFAITE,PCT_VICTOIRE,DUREE_MATCH,TIR REUSSI,...,turnoverRatio,effectiveFieldGoalPercentage,trueShootingPercentage,usagePercentage,estimatedUsagePercentage,estimatedPace,pace,pacePer40,possessions,PIE
0,21300002,1610612741,2013-10-29,CHI @ MIA,L,0,1,0.000,240,35,...,19.4,0.464,0.510,1.0,0.198,100.44,98.50,82.08,98.0,0.401
1,21300018,1610612741,2013-10-31,CHI vs. NYK,W,1,1,0.500,240,31,...,21.3,0.428,0.486,1.0,0.199,92.26,90.00,75.00,89.0,0.555
2,21300034,1610612741,2013-11-02,CHI @ PHI,L,1,2,0.333,240,42,...,18.0,0.468,0.513,1.0,0.199,100.64,99.50,82.92,100.0,0.518
3,21300061,1610612741,2013-11-06,CHI @ IND,L,1,3,0.250,240,26,...,20.0,0.390,0.471,1.0,0.198,92.56,90.00,75.00,90.0,0.364
4,21300079,1610612741,2013-11-08,CHI vs. UTA,W,2,3,0.400,240,38,...,22.6,0.549,0.584,1.0,0.196,94.50,93.00,77.50,93.0,0.756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,22300907,1610612741,2024-03-07,CHI @ GSW,W,31,32,0.492,240,46,...,13.6,0.621,0.644,1.0,0.198,105.72,103.50,86.25,103.0,0.508
856,22300917,1610612741,2024-03-09,CHI @ LAC,L,31,33,0.484,240,37,...,12.6,0.506,0.540,1.0,0.201,96.64,94.50,78.75,95.0,0.434
857,22300935,1610612741,2024-03-11,CHI vs. DAL,L,31,34,0.477,240,35,...,13.8,0.433,0.466,1.0,0.199,96.64,94.50,78.75,94.0,0.313
858,22300948,1610612741,2024-03-13,CHI @ IND,W,32,34,0.485,265,48,...,10.8,0.576,0.622,1.0,0.198,100.71,100.53,83.77,111.0,0.516
859,22300956,1610612741,2024-03-14,CHI vs. LAC,L,32,35,0.478,240,41,...,14.0,0.570,0.597,1.0,0.198,92.60,92.00,76.67,93.0,0.419

In [8]:
df_stat_last_10_perf = pd.DataFrame(columns=['gameId', 'teamId', 'GAME_DATE', 'DUEL','WL','NB_WIN', 'PCT_TIR_REUSSI_L10','PCT_3PTS_L10', 
                           'PCT_LANCER_FRANC_L10','estimatedOffensiveRating_L10', 'offensiveRating_L10',
                           'estimatedDefensiveRating_L10',
                           'defensiveRating_L10','estimatedNetRating_L10', 'netRating_L10', 'assistPercentage_L10',
                           'assistToTurnover_L10', 'assistRatio_L10','estimatedTeamTurnoverPercentage_L10', 'turnoverRatio_L10',
                           'effectiveFieldGoalPercentage_L10','trueShootingPercentage_L10', 'estimatedPace_L10', 'pace_L10',
                           'pacePer40_L10', 'PIE_L10'])

for team in list(set(df_stat['teamId'].tolist())):
    team_stats = df_stat[df_stat['teamId'] == team]
    team_stats.reset_index(drop=True, inplace=True)
    index = 11
    while index < len(team_stats):
        df_last_10_games = team_stats.iloc[max(0, index - 10):index]
        df_last_10_games.reset_index(drop=True, inplace=True)
        new_row = {"gameId" :  team_stats['gameId'][index],
                   "teamId" : team_stats['teamId'][index],
                   "GAME_DATE" : team_stats['GAME_DATE'][index],
                   "DUEL" : team_stats['DUEL'][index],
                   "WL" : team_stats['WL'][index],
                   "NB_WIN" : (df_last_10_games['WL'] == 'W').sum(),
                   "PCT_TIR_REUSSI_L10" : df_last_10_games['PCT_TIR_REUSSI'].mean(),
                   "PCT_3PTS_L10" : df_last_10_games['PCT_3PTS'].mean(),
                   "PCT_LANCER_FRANC_L10" : df_last_10_games['PCT_LANCER_FRANC'].mean(),
                   "estimatedOffensiveRating_L10" : df_last_10_games['estimatedOffensiveRating'].mean(),
                   "offensiveRating_L10" : df_last_10_games['offensiveRating'].mean(),
                   "estimatedDefensiveRating_L10" : df_last_10_games['estimatedDefensiveRating'].mean(),
                   "defensiveRating_L10" : df_last_10_games['defensiveRating'].mean(),
                   "estimatedNetRating_L10" : df_last_10_games['estimatedNetRating'].mean(),
                   "netRating_L10" : df_last_10_games['netRating'].mean(),
                   "assistPercentage_L10" : df_last_10_games['assistPercentage'].mean(),
                   "assistToTurnover_L10" : df_last_10_games['assistToTurnover'].mean(),
                   "assistRatio_L10" : df_last_10_games['assistRatio'].mean(),
                   "estimatedTeamTurnoverPercentage_L10" : df_last_10_games['estimatedTeamTurnoverPercentage'].mean(),
                   "turnoverRatio_L10" : df_last_10_games['turnoverRatio'].mean(),
                   "effectiveFieldGoalPercentage_L10" : df_last_10_games['effectiveFieldGoalPercentage'].mean(),
                   "trueShootingPercentage_L10" : df_last_10_games['trueShootingPercentage'].mean(),
                   "estimatedPace_L10" : df_last_10_games['estimatedPace'].mean(),
                   "pace_L10" : df_last_10_games['pace'].mean(),
                   "pacePer40_L10" : df_last_10_games['pacePer40'].mean(),
                   "PIE_L10" : df_last_10_games['PIE'].mean()}
        df_stat_last_10_perf.loc[len(df_stat_last_10_perf)] = new_row
        index += 1
df_stat_last_10_perf

,gameId,teamId,GAME_DATE,DUEL,WL,NB_WIN,PCT_TIR_REUSSI_L10,PCT_3PTS_L10,PCT_LANCER_FRANC_L10,estimatedOffensiveRating_L10,...,assistToTurnover_L10,assistRatio_L10,estimatedTeamTurnoverPercentage_L10,turnoverRatio_L10,effectiveFieldGoalPercentage_L10,trueShootingPercentage_L10,estimatedPace_L10,pace_L10,pacePer40_L10,PIE_L10
0,21300191,1610612753,2013-11-23,ORL @ MIA,L,4,0.4671,0.3785,0.7367,101.15,...,1.179,16.22,18.4793,18.72,0.5172,0.5530,98.725,97.039,80.866,0.4892
1,21300199,1610612753,2013-11-24,ORL vs. PHX,L,4,0.4667,0.3850,0.7480,101.54,...,1.174,16.35,18.7037,18.96,0.5186,0.5574,97.916,96.100,80.083,0.4912
2,21300213,1610612753,2013-11-26,ORL @ ATL,W,3,0.4574,0.3636,0.7559,100.16,...,1.258,16.46,17.9831,18.26,0.5050,0.5434,97.724,95.900,79.916,0.4692
3,21300216,1610612753,2013-11-27,ORL vs. PHI,W,3,0.4608,0.3588,0.7682,100.56,...,1.354,17.20,17.8090,18.08,0.5093,0.5486,97.544,95.750,79.791,0.4682
4,21300229,1610612753,2013-11-29,ORL vs. SAS,L,3,0.4644,0.3486,0.7631,100.88,...,1.343,17.22,17.9494,18.27,0.5124,0.5513,97.544,95.750,79.791,0.4662
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25613,22300900,1610612760,2024-03-06,OKC @ POR,W,7,0.4946,0.4056,0.8442,117.01,...,2.225,17.92,11.2556,11.36,0.5706,0.6038,104.410,102.900,85.749,0.5331
25614,22300914,1610612760,2024-03-08,OKC vs. MIA,W,8,0.5139,0.4103,0.8431,118.99,...,2.123,18.02,12.0673,12.15,0.5874,0.6222,104.074,102.650,85.541,0.5551
25615,22300931,1610612760,2024-03-10,OKC vs. MEM,W,8,0.5070,0.3938,0.8462,117.95,...,2.161,17.97,11.9483,11.99,0.5795,0.6132,103.176,102.150,85.125,0.5513
25616,22300941,1610612760,2024-03-12,OKC vs. IND,L,8,0.5049,0.3979,0.8545,118.33,...,2.288,18.44,11.8071,11.84,0.5810,0.6111,102.602,101.550,84.625,0.5615
25617,22300959,1610612760,2024-03-14,OKC vs. DAL,W,7,0.4927,0.3871,0.8572,116.49,...,2.313,18.36,11.6025,11.60,0.5665,0.5975,102.690,101.800,84.834,0.5436

In [9]:
df_stat_last_10_perf.to_csv('../dataset/team_stat_last_10.csv', index=False)

In [10]:
team_stats = df_stat[df_stat['teamId'] == '1610612744']
team_stats.reset_index(drop=True, inplace=True)
index = (team_stats['gameId'] == '21500336').idxmax()

df_last_10_games = team_stats.iloc[max(0, index - 10):index]
print((df_last_10_games['WL'] == 'W').sum())

10